### ISSUE TITLE
Problem with running pyPhewasModel

### ISSUE THREAD

**Issue by Cai-Sian** [MASILab/pyPheWAS#7] opened 2021-06-28 10:27 UTC
Hello
I was trying pyPheWAS with my data, and there seems to have problem in generating the regressions file 
As the figure attach below, I would like to know how to solve this problem
(the image only shows part of the error, but basically there are all the same type message)
For feature matrix, I used the file that created by bypyPhewasLookup, without any change/modified
![screen](https://user-images.githubusercontent.com/82924389/123621443-c84c9980-d83d-11eb-9648-94549d8cf9d7.PNG)
thanks a lot

**Comment by clineci** [comment] 2023-09-29 20:35
I realize that this issue was posted quite some time ago, but here's a guess for anyone else who ends up here: 

- I've never seen this error before, but I believe it could be caused by using a non-numerical covariate. (ex: sex being encoded by the strings "F" and "M"). So changing the categorical variable to a numerical representation would most likely fix it.
- For an example, check out the [synthetic dataset](https://github.com/MASILab/pyPheWAS/blob/master/synthetic_data/group.csv) added to the repo after this issue was first posted for a binary encoding of sex.

**Comment by BennettLandman** [comment] 2024-08-01 16:39
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.

**Closed as completed** 2024-08-01 16:45 UTC
